package com.geek.model.crawler.pojos;

import lombok.Data;

import java.util.Date;

@Data
public class ClIpPool {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_ip_pool.id
     *
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_ip_pool.supplier
     *
     * @mbggenerated
     */
    private String supplier;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_ip_pool.ip
     *
     * @mbggenerated
     */
    private String ip;
    /**
     * 端口号。
     */
    private int port;
    /**
     * 用户名。
     */
    private String username;
    /**
     * 密码。
     */
    private String password;
    /**
     * 错误码。
     */
    private Integer code;
    /**
     * 耗时。
     */
    private Integer duration;
    /**
     * 错误信息。
     */
    private String error;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_ip_pool.is_enable
     *
     * @mbggenerated
     */
    private Boolean isEnable;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_ip_pool.ranges
     *
     * @mbggenerated
     */
    private String ranges;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_ip_pool.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

}
